### ISSUE TITLE
Night Runways and Radio

### ISSUE THREAD

**Issue by RuschAirlines** [NVB9ALT/Realism-pack.#10]
Some of the runways don't appear at night, like papi and runway lights also some runways have been missing the radio feature when I add the Bookmarklet

**Comment by NVB9ALT** [comment]
The missing runway overlays are an intentional feature designed to reduce lag.
The missing lights, though, are interesting. I know that sometimes those runway lights take a while to turn on and off; could you double-check if the lights work properly without the Realism Pack?
Same thing for the missing ILS. Very interesting how preventing runway overlays from rendering also breaks that; again, could you check if it works properly without the Realism Pack?
Finally, could you give me an airport that has both of these issues so I could run my own tests? Thank you.

**Comment by RuschAirlines** [comment]
The one that I noticed was Runway 19R in Las Vegas and Palm Springs International. I think the ILS is just a problem with the game right now because it still wasn't working without the bookmarklet.

**Comment by RuschAirlines** [comment]
Thanks, didn't realize that.
