### ISSUE TITLE
Toggle Features (Suggestion for method)

### ISSUE THREAD

**Issue by SimV23** [NVB9ALT/Realism-pack.#13]
Hi, I have created an implementation of a feature i wanted for a while, which is the toggle feature. I don't know how to do menus yet, but if you can find out a way to add one, i have made it easy to toggle the features with a function. 
Here is the implementation:

https://github.com/SimV23/Realism-Pack-Toggle?organization=SimV23&organization=SimV23

I didn't do much to it, so I don't care if you use the code for yourself. It's mostly if statements.
I look forward to whatever you do with this

**Comment by NVB9ALT** [comment]
I refer you to this tutorial script I made: https://github.com/NVB9ALT/GeoFS-addon-libraries/blob/main/scripts/Adding%20toggle%20switches%20in%20options%20panel.js

If you can preserve all the functionality of the current realism pack while also adding your toggle options, I will be very happy and will gladly commit it to this repository. I was going to get around to this at some point since a lot of people have requested it, but to be honest I've been having too much fun with this rework of my F-14A addon aircraft I'm working on.

**Comment by NVB9ALT** [comment]
Also, I noticed that it re-runs realismGo() to update the currently-running code. Are you clearing all intervals and/or unloading all scripts before re-running realismGo()? Because if not, it could lead to issues where, for example, multiple instances of wingtip vortex condensation are running in parallel.

**Comment by SimV23** [comment]
It should clear everything in the update function, its a bit of a ducttaped way of going about it though.
I will look at all the resources and try to make it better, I will let you know when that happens.

Thank you

**Comment by kolos26** [comment]
I love the idea of turning scripts on and off! We can avoid to call the realismgo() too many times, by creating an interval, where we can easily add and remove functions. We can also keep the choices by saving it into localstorage, that I used in liverySelector, to save the starred liveries. If you need any help to do that, feel free to ask me any time!

**Comment by SimV23** [comment]
I sat down for today to figure out how to make it work. I think I have it working well now but there were a few little problems that i couldn't solve. For example the switches dont set themselves to the correct toggle when you load the code in. I looked at kolos livery changer and i pretty much copied what i saw there for the storage.

I hope you will be able to fix the problems more easily than me, i'm sorta new to the geofs code.

**Comment by kolos26** [comment]
For setting the toggles by script you need to add a "is-checked" class, for the label element.
I have taken a look to your code, it looks fine, there are no serious problems with that. As my school stuff is over, I will test it regularly.
 If you have any more questions just write them down! :) Thank you for doing this functionality, I was also thinking about something similar.

**Comment by NVB9ALT** [comment]
I tried to run your version, but it did have the script re-running issue which caused my FPS to drop to near zero, in addition to eventually crashing GeoFS and causing the options panel to fill with clouds/condensation toggles.

**Comment by SimV23** [comment]
that is rather strange, i did have the problem where the cloud buttons would fill up but I believe i fixed it by making it remove all of the previously generated switches.

I'm not sure how to fix a lot of the issues with it though, I was hoping to simply make a starting line that you all could fix up later so you dont have to start from scratch.

**Comment by NVB9ALT** [comment]
I believe I have a better idea anyway: putting each set of "stuff" inside an interval linked to a toggle switch so that, if the toggle switch is set to "on" it runs the code once and if it's set to "off" it clears all the intervals and scripts once. I'm also gonna see if I can implement saving your selections.


`/*toggle switch with value "geofs.example"*/`
`var run = 0;`
`exampleInt = setInterval(function(){`
`   if (geofs.example == 1 && run == 0) {`
`runCode()`
`run = 1`
`   }`
`   if (geofs.example == 0 && run == 1) {`
`deRunCode()`
`run = 0`
`   }`
`},100)`
