### ISSUE TITLE
realismGo is not defined on line 22 of the tampermonkey version.

### ISSUE THREAD

**Issue by Ampersand20** [NVB9ALT/Realism-pack.#14]
![image](https://user-images.githubusercontent.com/96956366/216741754-eb6afae1-97a3-4bf5-a2d3-779e07555e4c.png)
![image](https://user-images.githubusercontent.com/96956366/216741765-bca7dd86-4a3d-425b-9ca6-dda3e5ac55cb.png)

**Comment by NVB9ALT** [comment]
That's strange; I double-checked both the tampermonkey code and the core code that are in this GitHub repo and it should be able to execute the function in realismScript once realismScript has loaded. It's probably throwing this error because realismGo hasn't been mentioned anywhere in the tampermonkey code - try running the addon anyway; once realismScript has loaded, realismGo should be an executable function.

**Comment by Ampersand20** [comment]
do i have to add realismScript to this as well?

**Comment by NVB9ALT** [comment]
You shouldn't have to; the tampermonkey script will load realismScript from the url, and when it loads, execute the function that realismScript contains.

**Comment by Ampersand20** [comment]
It still isn't working. Tampermonkey says that there are no active
userscripts.

**Comment by NVB9ALT** [comment]
That's even stranger - the only reason I can think of for _that_ would be if you're running GeoFS on a proxy or something, where the domain of the website isn't "https://geo-fs.com". Try the bookmarklet version.

**Comment by Ampersand20** [comment]
okay.

**Comment by Ampersand20** [comment]
well the bookmarklet addon mostly works but the chat thing in options is
not responding.

**Comment by NVB9ALT** [comment]
yea it's been saying "typerror failed to fetch" for me, the chat site might be down. I'll fix it at some point.

Since the bookmarklet version appears to work, the issue is likely with the Tampermonkey version's triggers. If you're 100% sure you installed it correctly, I'll ask the wiki if anyone else a) uses the tampermonkey version, and b) is having issues with it. It's also possible that you run GeoFS in a strange way that upsets Tampermonkey.

**Comment by Ampersand20** [comment]
I'm on Mac is all.

**Comment by Ariakim-Taiyo** [comment]
That error is thrown because realismGo() is not defined _in this context._
realismGo() isn't actually defined anywhere in the program, rather it is in a script element that is added after the script has been executed.
Usually TM doesn't fail to compile from that sort of error, but it may help to define realismGo() as an empty function which will then be overwritten by the script tag so that TM can compile it. 
That's just speculation on my part, it is possible that something else is wrong, and it most likely is a difference between OSes. It could also be browser-based, since Chrome uses different extension architecture than Safari. 
It's always best to just define external things with non-constant definitions, such as var. Don't use const or let since those are static.

**Comment by kolos26** [comment]
I have solved the same problem in LiverySelector by adding this line to the end:
`window.realismGo = realismGo`
and I'm also calling  the `window.realismGo()` in the script.

**Comment by NVB9ALT** [comment]
I was thinking the same thing, I guess I just wasn't expecting Tampermonkey to be so rigorous with this sort of thing.

**Comment by DevHunter77** [comment]
I really don't like certain minorities

**Comment by NVB9ALT** [comment]
@Ampersand20 try the new version of the Tampermonkey in 10 minutes or so from the time of this message (to give raw.githack.com enough time to update)

**Comment by Ampersand20** [comment]
I'm using Brave as a browser, which is based on Chrome, but it still shouldn't be having any problems. I'll retry.
