### ISSUE TITLE
Aircraft black out after time change

### ISSUE THREAD

**Issue by AbnormalHuman** [NVB9ALT/Realism-pack.#18]
![Screenshot 2023-05-07 19 04 17](https://user-images.githubusercontent.com/127127127/236694755-6c0f4c4f-6bc3-430e-8de5-739100035c5f.png)

Hello,
I am running the code using Tampermonkey version on Chrome OS. Everytime when I set the time to night, and set the time back to daytime, the plane will black out.

Is this a code issue or the FPS lag?

**Comment by NVB9ALT** [comment]
I know that if you turn advanced atmosphere off and on again, it will cause this issue; when that happens, it's caused by the over-G blackout loading before the advanced atmosphere does. I don't know why changing time of day causes it - the most logical explanation is that the advanced atmosphere reloads when you set time from night to day, but I don't think this is the case. I'll ask the people on my Guilded server if the same effect happens to them.

Also, check the console - do any console errors pop up when this happens?

**Comment by AbnormalHuman** [comment]
Actually, it's changing the **set environment manually** option off then on blacking the plane and the surrounding terrain.

**Comment by NVB9ALT** [comment]
Oh that explains it - changing that setting forces the advanced atmosphere to reload, triggering the bug.

**Comment by AbnormalHuman** [comment]
Thank you.

**Comment by AbnormalHuman** [comment]
Yes

**Comment by AbnormalHuman** [comment]
I will report more issues if found.
