### ISSUE TITLE
Enhancements about airport lightinngs.

### ISSUE THREAD

**Issue by AbnormalHuman** [NVB9ALT/Realism-pack.#19]
I know that you would probably not add this to the script or make another add-on about this, but is it possible to give better airport lighting, such as putting taxiway outline lights for large airports?
Below is a video about the airport lighting. 

`https://www.youtube.com/watch?v=-xM-Y245kUo`

**Comment by NVB9ALT** [comment]
Not currently maintaining the project; talk to Kolos26. Keep in mind he may not be available for some time due to school.

I also think that taxiway lighting would be really cool; it's pretty much impossible to taxi around airports at night without it. I thought about an implementation several months ago, using the default runway lights system, but that implementation would be complex and involve things I don't understand.
Maybe try talking to Xavier about it?

**Comment by AbnormalHuman** [comment]
Sure, I will talk to Kolos26 about that.

**Comment by NVB9ALT** [comment]
Check their projects' READMEs for contact info, or try searching their username on the wiki.

**Comment by AbnormalHuman** [comment]
Speaking of enhancements to the project, when is the toggle feature going to be added?

**Comment by NVB9ALT** [comment]
Potentially soon.
