### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by NUBZRCOOL** [NVB9ALT/Realism-pack.#26]
Joystick inputs do not work when I have this addon enabled. The inputs are not detected at all.

**Comment by NVB9ALT** [comment]
Hmmm. This catches my attention because I have also been having issues with my joystick and GeoFS recently. I did a quick test and my joystick got messed up regardless of whether or not the Realism Pack was running, so at least it's not a universal issue. Any error messages in the console when you plug in the joystick or press "J"?

I noticed as well that you closed the issue a couple hours after posting it, did you figure out the cause yourself and fix it or...?

**Comment by NUBZRCOOL** [comment]
Yes, the joystick worked but the issue was that the controls were not being displayed in the options window so I could not tell if the controller was connected properly. It started working when I turned off the addon, set up the controls, and then turning the addon back on. I did not look for any console errors.

**Comment by NVB9ALT** [comment]
GeoFS seems to do that in general, regardless of whether the Realism Pack is running or not. It depends on whether you plugged the joystick in _before_ or _after_ you loaded GeoFS, but which order it has to be in also varies by device and I don't really know what's going on there. On my device, for example, I can't set up joystick controls unless I plug it in _after_ GeoFS loads, but on a different device I tried, it would only work if I plugged it in _before_ loading GeoFS.
