### ISSUE TITLE
Aircraft loading in before terrain

### ISSUE THREAD

**Issue by AbnormalHuman** [NVB9ALT/Realism-pack.#32]
The planes loaded in before the terrain, specifically after this recent update two days ago. This causes the thing to glitch the plane and terrain into pitch black. Can we fix the code a little bit?

**Comment by AbnormalHuman** [comment]
Also I discovered that after re-adding the runway layovers, the game forces the terrain to load before the plane, therefore solving the issue. But yours will prob be still removed, so I guess we gotta find another way...

**Comment by NVB9ALT** [comment]
Can you send me a screenshot? Because based on your description it may be a known issue with the over-G blackout shader.

**Comment by AbnormalHuman** [comment]
Ye I think is that. I will send a screenshot later to you if that's OK?

**Comment by AbnormalHuman** [comment]
[Screen recording 2024-01-09 08.02.56.webm](https://github.com/NVB9ALT/Realism-pack./assets/127127127/49925ef7-37fc-40d0-beb5-11f735f8ba59)

**Comment by NVB9ALT** [comment]
Ye that's what I thought was happening. The cause of that glitch is the shader for the over-G blackout loading before the advanced atmosphere shader does. There is a statement in the code that delays loading the over-G blackout until the advanced atmosphere is loaded, in order to prevent this glitch, but I guess it didn't work this time? Are you using the Tampermonkey version?

**Comment by NVB9ALT** [comment]
The recent addition of Ariakim's shaders might have something to do with it, but I'm not sure how it's causing the glitch, unless it's causing the advanced atmosphere to load twice...

**Comment by AbnormalHuman** [comment]
Ye might be that...

**Comment by AbnormalHuman** [comment]
Yes, I am using the Tampermonkey script. Is there a way to have a 15-second delay before the addon is activated?

**Comment by NVB9ALT** [comment]
That explains it. When you run the bookmarklet version _after_ the advanced atmosphere loads, everything works fine AFAIK. I will see what I can do when I get home from school so I can use my personal computer.

**Comment by AbnormalHuman** [comment]
Ye, the Tampermonkey script should have a 15-second delay before it starts working.

**Comment by NVB9ALT** [comment]
I did some testing when I got home from school yesterday, and found that running the bookmarklet before advanced atmosphere loads causes the glitch as well. This is odd, because there is an "if" statement in the code specifically to stop this from happening.
Problem is, a timer delay isn't a good fix. The time it takes for GeoFS to load fully can vary from computer to computer, browser to browser, and maybe even on how many tabs you have open. Maybe I'll try and set up a script loading order system, so that the over-G blackout loads _after_ Ariakim's shaders (as that's my best guess as to what the problem is).

**Comment by NVB9ALT** [comment]
The over-G blackout shader now (in theory) only loads if the SSR shaders are loaded. See if:
- the glitch doesn't happen anymore
- the over-G blackout still works

**Comment by AbnormalHuman** [comment]
Nice!!!

**Comment by NVB9ALT** [comment]
Darn. Not sure what to do now. The easiest thing to do would be to delete the Tampermonkey version, but I want to keep that option available.

**Comment by NVB9ALT** [comment]
It now attempts to load the over-G blackout every 20 seconds, hopefully giving enough time for things to sort out. See if it works.

**Comment by AbnormalHuman** [comment]
Ye I know coding sometimes can be hard...

**Comment by Gamer1029384756** [comment]
I have the same problem as well.

**Comment by Gamer1029384756** [comment]
I’m using the tampermonkey version too.

**Comment by Gamer1029384756** [comment]
Does the bookmark let version work?

**Comment by NVB9ALT** [comment]
It now only loads the SSR shaders once the over-G blackout shader is loaded, see if it works.

**Comment by NVB9ALT** [comment]
Making the software not be a buggy broken mess is like the bare minimum from a developer, but thanks for the thanks anyways.

**Comment by Gamer1029384756** [comment]
I’ll check in a few days.

**Comment by Gamer1029384756** [comment]
Thanks anyway
