### ISSUE TITLE
Code Updates

### ISSUE THREAD

**Issue by Gamer1029384756** [NVB9ALT/Realism-pack.#33]
I have noticed from the date last updated that the main.js code has regular updates but the Tampermonkey-code.js hasn’t gotten those updates. Can you update the tampermonkey code as well? Please inform me if I’m wrong.

**Comment by NVB9ALT** [comment]
The Tampermonkey code and the bookmarklet code are basically the same. They both add the script "main.js" to GeoFS, which is what actually implements the addon features.

On an unrelated note, do you use the Tampermonkey version? I ask because a number of people have said that the Tampermonkey version doesn't work, and I'm not sure if it works at all.

**Comment by Gamer1029384756** [comment]
Yea I do. I recently use the main.js because the tampermonkey has a glitch.

**Comment by NVB9ALT** [comment]
Well fortunately for you the Tampermonkey version no longer has that glitch! (I hope XD)
