### ISSUE TITLE
aircraft?

### ISSUE THREAD

**Issue by B-don-don** [NVB9ALT/Realism-pack.#5]
in the code, there is an element for a F-18 and MIG-17. Are those just variable names, or are they actual new aircraft? If they are actual aircraft, how do you get them? 
![image](https://user-images.githubusercontent.com/114553146/199872250-d1d6b06b-ec37-47b9-bba2-b9feac2d603a.png)

**Comment by NVB9ALT** [comment]
This is for my [addon aircraft](https://github.com/NVB9ALT/Addon-Aircraft-and-Parts). The Realism Pack's condensation effects require that geofs.debug.update be modified, in order to ensure that the 3d models used for those effects are placed on the aircraft's position in sync with frame rendering. Because the addon aircraft use the exact same method of loading the model, it made sense to put the model management in the Realism Pack so the Realism Pack and Addon Aircraft don't conflict with each other.
